<#assign artifact_attributes = 
        {"TSK_WEB_BOOKMARK":["Source File","Program Name","Title","Domain","Date Created","URL"],
         "TSK_GEN_INFO":["Source File","Created","Modified","Accessed"],
        "TSK_WEB_COOKIE":["Source File","Program Name","Date/Time","Value"],
        "TSK_WEB_HISTORY":["Source File","Program Name","Date Accessed","Title","URL","Referrer URL"],
        "TSK_WEB_DOWNLOAD":["Source File","Path","Program Name","Date Accessed","Domain","URL"],
        "TSK_RECENT_OBJ":["Source File","Path","Path ID","Date/Time"],
        "TSK_GPS_TRACKPOINT":["Source File"],
        "TSK_INSTALLED_PROG":["Source File"],
        "TSK_KEYWORD_HIT":["Source File"],
        "TSK_HASHSET_HIT":["Source File"],
        "TSK_DEVICE_ATTACHED":["Source File","Device Make","Device Model","Device ID","Date/Time"],
        "TSK_INTERESTING_FILE_HIT":["Source File"],
        "TSK_EMAIL_MSG":["Source File"],
        "TSK_EXTRACTED_TEXT":["Source File"],
        "TSK_WEB_SEARCH_QUERY":["Source File","Program Name","Text","Domain","Date Accessed"],
        "TSK_METADATA_EXIF":["Source File","Device Make","Device Model","Date Created"],
        "TSK_TAG_FILE":["Source File"],
        "TSK_TAG_ARTIFACT":["Source File"],
        "TSK_OS_INFO":["Source File","Processor Architecture"],
        "TSK_OS_ACCOUNT":["Source File"],
        "TSK_SERVICE_ACCOUNT":["Source File"],
        "TSK_TOOL_OUTPUT":["Source File","Program Name","Text"],
        "TSK_CONTACT":["Source File"],
        "TSK_MESSAGE":["Source File"],
        "TSK_CALLLOG":["Source File"],
        "TSK_MESSAGE":["Source File"],
        "TSK_CALENDAR_ENTRY":["Source File"],
        "TSK_SPEED_DIAL_ENTRY":["Source File"],
        "TSK_BLUETOOTH_PAIRING":["Source File"],
        "TSK_GPS_LAST_KNOWN_LOCATION":["Source File"],
        "TSK_GPS_SEARCH":["Source File"],
        "TSK_PROG_RUN":["Source File"],
        "TSK_ENCRYPTION_DETECTED":["Source File"],
        "TSK_EXT_MISMATCH_DETECTED":["Source File","Source File","Extension","MIME Type"],
        "TSK_INTERESTING_ARTIFACT_HIT":["Source File"],
        "TSK_GPS_ROUTE":["Source File"]}>
